import { Schema } from "effect";
import type { Option } from "effect";
import type { Action } from "@cuttlekit/common/client";
import type { SandboxContext } from "../sandbox/manager.js";
import type { ComponentSpec } from "../vdom/vdom.js";

// ============================================================
// Effect Schemas
// ============================================================

export const PatchSchema = Schema.Struct({
  selector: Schema.String,
  text: Schema.optional(Schema.String),
  attr: Schema.optional(
    Schema.Record({ key: Schema.String, value: Schema.NullOr(Schema.String) })
  ),
  append: Schema.optional(Schema.String),
  prepend: Schema.optional(Schema.String),
  html: Schema.optional(Schema.String),
  remove: Schema.optional(Schema.Literal(true)),
});

export const PatchArraySchema = Schema.Array(PatchSchema);

// Schema for define ops (component registration)
export const DefineOpSchema = Schema.Struct({
  op: Schema.Literal("define"),
  tag: Schema.String,
  props: Schema.Array(Schema.String),
  template: Schema.String,
});

// Schema for LLM responses — discriminated on `op`
export const PatchesResponse = Schema.Struct({
  op: Schema.Literal("patches"),
  patches: PatchArraySchema,
});

export const FullResponse = Schema.Struct({
  op: Schema.Literal("full"),
  html: Schema.String,
});

export const LLMResponseSchema = Schema.Union(
  PatchesResponse,
  FullResponse,
  DefineOpSchema,
);

export type LLMResponse = typeof LLMResponseSchema.Type;

// Full response schema includes stats (generated by code, not LLM)
export type UnifiedResponse =
  | LLMResponse
  | {
      op: "stats";
      cacheRate: number;
      tokensPerSecond: number;
      mode: "patches" | "full";
      patchCount: number;
      ttft: number;
      ttc: number;
    };

// ============================================================
// Exported Types
// ============================================================

export type UnifiedGenerateOptions = {
  sessionId: string;
  currentHtml: Option.Option<string>;
  promptHtml?: Option.Option<string>;
  catalog: Option.Option<string>;
  actions: readonly Action[];
  modelId?: string;
  sandboxCtx?: SandboxContext;
  registrySpecs?: readonly ComponentSpec[];
};

// ============================================================
// Retry Types - Immutable state for functional retry loop
// ============================================================

export type Message = {
  readonly role: "system" | "user" | "assistant";
  readonly content: string;
};


// Usage types for token aggregation
export type Usage = {
  inputTokens?: number;
  outputTokens?: number;
  totalTokens?: number;
  inputTokenDetails?: { cacheReadTokens?: number };
};

export type AggregatedUsage = {
  inputTokens: number;
  outputTokens: number;
  totalTokens: number;
  cachedTokens: number;
};
